# RTv1 config file

camera:
  - eye:
  0.0 0 0
  - look_at: 
  0 0 1
  - fov:
  60.0

light:
  - origin:
  12 21 456
  - intensity:
  60.0

light:
  - origin:
  10.2 13.4 16.9
  - intensity:
  60.0

object:
  - name:
    sphere
  - center:
  0 0 15
  - radius:
  2.0
  - color:
    20

object:
  - name:
    cylinder
  - center:
  20 0 30
  - radius:
  2
  - color:
    20

object:
  # Simple comment
  - name:
    cone
  - center:
  1 2 4
  - radius:
  2
  - color:
    20

object:  
  # Points
  - name:
    plane
  - center:
  0 1 0
  radius:
  0
  - color:
    20
